Update sanctum-lst-list.toml
igneous-labs/sanctum-lst-list pull request #38
Opened 2024-03-12 14:36 UTC by fplord

new SPL pool

2024-03-12 23:35 UTC, billythedummy requested changes

2024-03-12 23:35 UTC, billythedummy commented on sanctum-lst-list.toml
> +    { name = "The Vault", symbol = "vSOL", mint = "vSoLxydx6akxyMD9XEcPvGYNGq6Nn66oqVb3UkGkei7", decimals = 9, token_program = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA", logo_uri = "https://cloud
```suggestion
    { name = "The Vault", symbol = "vSOL", mint = "vSoLxydx6akxyMD9XEcPvGYNGq6Nn66oqVb3UkGkei7", decimals = 9, token_program = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA", logo_uri = "https://cloudflare-ipfs.com/ipfs/bafkreig55mf3lazzbgndiqyqvdmchdsykvvebww7cqlws6ywgog5xfdzta", pool = { program = "Spl", pool = "Fu9BYC6tWBo1KMKaP3CFoKfRhqv9akmy3DuYwnCyWiyC", validator_list = "3wsE11pAjCE3sCwokhD5kgi5cjv6hi3DGAkxXB5MMHKL" } },
```

2024-03-12 23:52 UTC, billythedummy approved these changes

2024-03-13 15:46 UTC, f8122dac91 approved these changes

2024-03-14 23:55 UTC, merged