update kumaSOL logo
igneous-labs/sanctum-lst-list pull request #82
Opened 2024-06-26 19:26 UTC by alkinemk

2024-06-27 01:15 UTC, billythedummy requested changes

2024-06-27 01:15 UTC, billythedummy commented on sanctum-lst-list.toml
> +logo_uri = "https://arweave.net/V2W_NcNoLjfDRS_-_llDIom04X8BY35V5yOelv-ATkI"
```suggestion
logo_uri = "https://arweave.net/dBlyZZ8SRU8gbBLB_Ahil_NXCtsh67PI10mTq9qcMVA"
```

this appears to be the metadata json uri, edited link is whats linked in the json file

2024-07-05 08:40 UTC, alkinemk commented
bruh i don't understand why it's still saying "change requested"

2024-07-05 08:56 UTC, billythedummy approved these changes

2024-07-05 08:56 UTC, merged